"""
core/sandbox/code_executor.py
Isolated Code Execution and Runtime Verification Sandbox.
Safely executes and validates Python and generic code snippets generated by AI Agents.
Catches RuntimeErrors, SyntaxErrors, ZeroDivisionErrors, infinite loops, and timeout violations.
"""

import sys
import time
import subprocess
import tempfile
from pathlib import Path
from dataclasses import dataclass
from typing import Optional, Dict, Any

@dataclass
class ExecutionResult:
    success: bool
    stdout: str = ""
    stderr: str = ""
    error_type: Optional[str] = None
    error_message: Optional[str] = None
    traceback: Optional[str] = None
    execution_time_ms: float = 0.0
    timeout_exceeded: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "success": self.success,
            "stdout": self.stdout,
            "stderr": self.stderr,
            "error_type": self.error_type,
            "error_message": self.error_message,
            "traceback": self.traceback,
            "execution_time_ms": self.execution_time_ms,
            "timeout_exceeded": self.timeout_exceeded
        }


class CodeSandboxExecutor:
    """
    Sandboxed Code Executor that runs code in an isolated subprocess with strict timeouts.
    """

    def __init__(self, default_timeout_sec: float = 3.0):
        self.default_timeout_sec = default_timeout_sec

    def execute_python_code(self, code_str: str, timeout_sec: Optional[float] = None) -> ExecutionResult:
        """
        Executes a Python code snippet in an isolated subprocess.
        Returns an ExecutionResult with detailed error analysis.
        """
        if not code_str or not code_str.strip():
            return ExecutionResult(success=True, stdout="[Empty code snippet]")

        timeout = timeout_sec or self.default_timeout_sec
        start_time = time.perf_counter()

        # Write code to a temporary file
        with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False, encoding="utf-8") as temp_file:
            temp_path = Path(temp_file.name)
            temp_file.write(code_str)

        try:
            cmd = [sys.executable, str(temp_path)]
            proc = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=timeout,
                encoding="utf-8",
                errors="replace"
            )
            elapsed_ms = (time.perf_counter() - start_time) * 1000.0

            if proc.returncode == 0:
                return ExecutionResult(
                    success=True,
                    stdout=proc.stdout.strip(),
                    stderr=proc.stderr.strip(),
                    execution_time_ms=round(elapsed_ms, 2)
                )
            else:
                stderr = proc.stderr.strip()
                error_type, error_msg = self._parse_python_error(stderr)
                return ExecutionResult(
                    success=False,
                    stdout=proc.stdout.strip(),
                    stderr=stderr,
                    error_type=error_type,
                    error_message=error_msg,
                    traceback=stderr,
                    execution_time_ms=round(elapsed_ms, 2)
                )

        except subprocess.TimeoutExpired:
            elapsed_ms = (time.perf_counter() - start_time) * 1000.0
            return ExecutionResult(
                success=False,
                error_type="TimeoutExpired",
                error_message=f"Chương trình chạy vượt quá giới hạn thời gian ({timeout}s) - nghi ngờ vòng lặp vô hạn.",
                execution_time_ms=round(elapsed_ms, 2),
                timeout_exceeded=True
            )
        except Exception as ex:
            elapsed_ms = (time.perf_counter() - start_time) * 1000.0
            return ExecutionResult(
                success=False,
                error_type=type(ex).__name__,
                error_message=str(ex),
                execution_time_ms=round(elapsed_ms, 2)
            )
        finally:
            try:
                if temp_path.exists():
                    temp_path.unlink()
            except Exception:
                pass

    def verify_code_snippet(self, code_str: str, tech_stack: str = "python") -> ExecutionResult:
        """
        Language-adaptive code verification. Runs Python code directly,
        or performs basic syntax validation for other languages.
        """
        tech_lower = tech_stack.lower()
        if "python" in tech_lower:
            return self.execute_python_code(code_str)

        # For non-Python stacks, perform static checks (e.g. check for unclosed brackets/quotes)
        start_time = time.perf_counter()
        if code_str.count("{") != code_str.count("}") or code_str.count("(") != code_str.count(")"):
            elapsed_ms = (time.perf_counter() - start_time) * 1000.0
            return ExecutionResult(
                success=False,
                error_type="SyntaxWarning",
                error_message="Phát hiện dấu đóng/mở ngoặc không cân xứng trong mã nguồn.",
                execution_time_ms=round(elapsed_ms, 2)
            )

        elapsed_ms = (time.perf_counter() - start_time) * 1000.0
        return ExecutionResult(
            success=True,
            stdout=f"Static syntax verification passed for {tech_stack}",
            execution_time_ms=round(elapsed_ms, 2)
        )

    def _parse_python_error(self, stderr: str) -> tuple[str, str]:
        """Extracts the exception class name and message from stderr."""
        lines = [line.strip() for line in stderr.splitlines() if line.strip()]
        if not lines:
            return "RuntimeError", "Mã nguồn thực thi thất bại không có thông điệp lỗi."

        last_line = lines[-1]
        if ":" in last_line:
            parts = last_line.split(":", 1)
            return parts[0].strip(), parts[1].strip()
        return "RuntimeError", last_line


_default_sandbox = CodeSandboxExecutor()

def execute_code_snippet(code: str, tech_stack: str = "python", timeout_sec: float = 3.0) -> ExecutionResult:
    """Convenience functional interface for sandboxed execution."""
    if "python" in tech_stack.lower():
        return _default_sandbox.execute_python_code(code, timeout_sec=timeout_sec)
    return _default_sandbox.verify_code_snippet(code, tech_stack=tech_stack)
