"""add missing columns

Revision ID: 3492a208f2fc
Revises: fef6e44f2c74
Create Date: 2026-07-20 19:22:04.179894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3492a208f2fc'
down_revision: Union[str, None] = 'fef6e44f2c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('session_id', sa.Integer(), nullable=True))
    op.add_column('artifacts', sa.Column('versions', sa.JSON(), nullable=True))
    op.alter_column('artifacts', 'lesson_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('artifacts', 'content',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.create_foreign_key(None, 'artifacts', 'sessions', ['session_id'], ['id'])
    op.add_column('lessons', sa.Column('order_index', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('order_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'order_index')
    op.drop_column('lessons', 'order_index')
    op.drop_constraint(None, 'artifacts', type_='foreignkey')
    op.alter_column('artifacts', 'content',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('artifacts', 'lesson_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('artifacts', 'versions')
    op.drop_column('artifacts', 'session_id')
    # ### end Alembic commands ###
